# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: enum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='enum.proto',
  package='example.enumeration',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\nenum.proto\x12\x13\x65xample.enumeration\"I\n\x0b\x45numMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12.\n\x08\x64\x61y_name\x18\x02 \x01(\x0e\x32\x1c.example.enumeration.DayName*r\n\x07\x44\x61yName\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06SUNDAY\x10\x01\x12\n\n\x06MONDAY\x10\x02\x12\x0b\n\x07TUESDAY\x10\x03\x12\r\n\tWEDNESDAY\x10\x04\x12\x0c\n\x08THURSDAY\x10\x05\x12\n\n\x06\x46RIDAY\x10\x06\x12\x0c\n\x08SATURDAY\x10\x07\x62\x06proto3'
)

_DAYNAME = _descriptor.EnumDescriptor(
  name='DayName',
  full_name='example.enumeration.DayName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUNDAY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MONDAY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TUESDAY', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WEDNESDAY', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THURSDAY', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIDAY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SATURDAY', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=110,
  serialized_end=224,
)
_sym_db.RegisterEnumDescriptor(_DAYNAME)

DayName = enum_type_wrapper.EnumTypeWrapper(_DAYNAME)
UNKNOWN = 0
SUNDAY = 1
MONDAY = 2
TUESDAY = 3
WEDNESDAY = 4
THURSDAY = 5
FRIDAY = 6
SATURDAY = 7



_ENUMMESSAGE = _descriptor.Descriptor(
  name='EnumMessage',
  full_name='example.enumeration.EnumMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='example.enumeration.EnumMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day_name', full_name='example.enumeration.EnumMessage.day_name', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=108,
)

_ENUMMESSAGE.fields_by_name['day_name'].enum_type = _DAYNAME
DESCRIPTOR.message_types_by_name['EnumMessage'] = _ENUMMESSAGE
DESCRIPTOR.enum_types_by_name['DayName'] = _DAYNAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnumMessage = _reflection.GeneratedProtocolMessageType('EnumMessage', (_message.Message,), {
  'DESCRIPTOR' : _ENUMMESSAGE,
  '__module__' : 'enum_pb2'
  # @@protoc_insertion_point(class_scope:example.enumeration.EnumMessage)
  })
_sym_db.RegisterMessage(EnumMessage)


# @@protoc_insertion_point(module_scope)
